import { describe, it, before } from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";

describe("service worker (public/sw.js, generated by next build)", () => {
  const sw = readFileSync(new URL("../public/sw.js", import.meta.url), "utf8");
  const routes = [...sw.matchAll(/registerRoute\((.+?),new [a-z]\.(\w+)(?:\(\{cacheName:"([^"]+)")?/g)].map((m) => ({
    matcher: m[1],
    handler: m[2],
    cacheName: m[3],
  }));

  it("registers routes", () => assert.ok(routes.length > 5));

  it("makes every cross-origin request network-only, ahead of any caching route", () => {
    const i = routes.findIndex((r) => r.matcher.includes("self.origin!==") && r.handler === "NetworkOnly");
    assert.ok(i >= 0, "cross-origin NetworkOnly route missing");
    const cachingBefore = routes.slice(0, i).filter((r) => r.handler !== "NetworkOnly" && r.matcher !== '"/"');
    assert.deepEqual(cachingBefore, []);
  });

  it("makes same-origin /api/ network-only, ahead of any caching route", () => {
    const i = routes.findIndex((r) => r.matcher.includes('startsWith("/api/")') && r.handler === "NetworkOnly");
    assert.ok(i >= 0, "/api/ NetworkOnly route missing");
    const cachingBefore = routes.slice(0, i).filter((r) => r.handler !== "NetworkOnly" && r.matcher !== '"/"');
    assert.deepEqual(cachingBefore, []);
  });

  it("no longer has the default apis / cross-origin caches", () => {
    const names = routes.map((r) => r.cacheName);
    assert.ok(!names.includes("apis"));
    assert.ok(!names.includes("cross-origin"));
  });

  it("the cross-origin matcher function behaves as intended", () => {
    const src = routes.find((r) => r.matcher.includes("self.origin!=="))!.matcher;
    const fn = new Function("self", `return ${src}`)({ origin: "https://app.example" });
    assert.equal(fn({ url: new URL("https://api.example/v1/claims") }), true);
    assert.equal(fn({ url: new URL("https://bucket.s3.amazonaws.com/claims/x.pdf?X-Amz-Signature=1") }), true);
    assert.equal(fn({ url: new URL("https://app.example/claims") }), false);
  });
});

describe("next.config.mjs security headers", () => {
  let prodHeaders: Map<string, string>;
  let devHeaders: Map<string, string>;
  let prodConfig: any;

  const load = async (nodeEnv: string, tag: string) => {
    process.env.NODE_ENV = nodeEnv;
    process.env.NEXT_PUBLIC_API_BASE_URL = "https://api.example.test/v1";
    const mod = await import(`../next.config.mjs?${tag}`);
    const config = mod.default;
    const [rule] = await config.headers();
    assert.equal(rule.source, "/:path*");
    return { config, headers: new Map<string, string>(rule.headers.map((h: any) => [h.key, h.value])) };
  };

  before(async () => {
    const prod = await load("production", "prod");
    prodConfig = prod.config;
    prodHeaders = prod.headers;
    devHeaders = (await load("development", "dev")).headers;
  });

  it("blocks framing (clickjacking)", () => {
    assert.equal(prodHeaders.get("X-Frame-Options"), "DENY");
    assert.match(prodHeaders.get("Content-Security-Policy")!, /frame-ancestors 'none'/);
  });

  it("limits connections to self and the API origin", () => {
    assert.match(prodHeaders.get("Content-Security-Policy")!, /connect-src 'self' https:\/\/api\.example\.test(;|$)/);
  });

  it("does not allow eval or websockets in production", () => {
    const csp = prodHeaders.get("Content-Security-Policy")!;
    assert.ok(!csp.includes("'unsafe-eval'"));
    assert.ok(!/connect-src[^;]*ws:/.test(csp));
  });

  it("allows eval and websockets in development (fast refresh)", () => {
    const csp = devHeaders.get("Content-Security-Policy")!;
    assert.ok(csp.includes("'unsafe-eval'"));
    assert.match(csp, /connect-src[^;]*ws:/);
  });

  it("locks down plugins, base URI and form targets", () => {
    const csp = prodHeaders.get("Content-Security-Policy")!;
    for (const directive of ["object-src 'none'", "base-uri 'self'", "form-action 'self'", "default-src 'self'"]) {
      assert.ok(csp.includes(directive), directive);
    }
  });

  it("sends the other hardening headers", () => {
    assert.equal(prodHeaders.get("X-Content-Type-Options"), "nosniff");
    assert.equal(prodHeaders.get("Referrer-Policy"), "strict-origin-when-cross-origin");
    assert.match(prodHeaders.get("Strict-Transport-Security")!, /max-age=\d+/);
    assert.ok(prodHeaders.get("Permissions-Policy"));
  });

  it("hides the x-powered-by header", () => {
    assert.equal(prodConfig.poweredByHeader, false);
  });
});
